// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnpLdknvtfnwww7w-uDajEQhCv9ACjCtc',
    appId: '1:500675737228:web:cf3e275af2266df4f82da9',
    messagingSenderId: '500675737228',
    projectId: 'lab-manager-748e8',
    authDomain: 'lab-manager-748e8.firebaseapp.com',
    storageBucket: 'lab-manager-748e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaL8qlb9fCSyHtHu3M0JLnTZ7oX0GjadI',
    appId: '1:500675737228:android:97c9083d7797ba22f82da9',
    messagingSenderId: '500675737228',
    projectId: 'lab-manager-748e8',
    storageBucket: 'lab-manager-748e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLnZlh1LV5av-8qZ2hoDZSpvQ1RYMv9Ys',
    appId: '1:500675737228:ios:e789d5a264e13df0f82da9',
    messagingSenderId: '500675737228',
    projectId: 'lab-manager-748e8',
    storageBucket: 'lab-manager-748e8.firebasestorage.app',
    iosClientId: '500675737228-dq52pc4lvtjpkhnc7hdbg0qq821a3bim.apps.googleusercontent.com',
    iosBundleId: 'org.cert.etcs.lab.etcsLabManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLnZlh1LV5av-8qZ2hoDZSpvQ1RYMv9Ys',
    appId: '1:500675737228:ios:e789d5a264e13df0f82da9',
    messagingSenderId: '500675737228',
    projectId: 'lab-manager-748e8',
    storageBucket: 'lab-manager-748e8.firebasestorage.app',
    iosClientId: '500675737228-dq52pc4lvtjpkhnc7hdbg0qq821a3bim.apps.googleusercontent.com',
    iosBundleId: 'org.cert.etcs.lab.etcsLabManager',
  );
}
